import type { Role, RoleEdge } from "./schema";

/** RATS의 여섯 핵심 역할과 TDX 워크로드 경계를 함께 표시한다. */
export const roles = [
  {
    id: "attester",
    label: "Attester",
    plane: "attestation",
    description: "측정된 환경을 대표해 Evidence를 제시한다.",
    policyOwner: false,
  },
  {
    id: "verifier",
    label: "Verifier",
    plane: "attestation",
    description: "Evidence와 collateral을 검증하고 Attestation Result를 만든다.",
    policyOwner: false,
  },
  {
    id: "relying-party",
    label: "Relying Party",
    plane: "control",
    description: "Attestation Result를 받아 접근 또는 서비스 제공 여부를 결정한다.",
    policyOwner: false,
  },
  {
    id: "endorser",
    label: "Endorser",
    plane: "collateral",
    description: "검증에 필요한 Endorsement와 참조값을 제공하는 역할이다.",
    policyOwner: false,
  },
  {
    id: "reference-value-provider",
    label: "Reference Value Provider",
    plane: "control",
    description: "정상 상태를 판단할 기준값을 제공한다.",
    policyOwner: false,
  },
  {
    id: "policy-owner",
    label: "Policy Owner",
    plane: "control",
    description: "허용 측정값, TCB 상태, 키 공개 기준을 소유한다.",
    policyOwner: true,
  },
  {
    id: "trusted-domain",
    label: "Trust Domain (TD)",
    plane: "workload",
    description: "Intel TDX로 격리된 실행 경계이며 Quote의 측정 대상이다.",
    policyOwner: false,
  },
  {
    id: "guest-agent",
    label: "Guest Agent",
    plane: "workload",
    description: "TD 내부에서 Quote 생성을 요청하고 검증 요청을 전달한다.",
    policyOwner: false,
  },
  {
    id: "container",
    label: "Container",
    plane: "workload",
    description: "비밀키를 필요로 하는 애플리케이션 워크로드다.",
    policyOwner: false,
  },
  {
    id: "pcs",
    label: "Intel PCS",
    plane: "collateral",
    description: "Intel Provisioning Certification Service가 원본 collateral을 제공한다.",
    policyOwner: false,
  },
  {
    id: "pccs",
    label: "PCCS",
    plane: "collateral",
    description: "Intel collateral을 캐시해 Verifier에 제공한다.",
    policyOwner: false,
  },
  {
    id: "key-broker",
    label: "Key Broker",
    plane: "control",
    description: "허용된 Attestation Result에만 workload key를 릴리스한다.",
    policyOwner: false,
  },
] as const satisfies readonly Role[];

export const roleEdges = [
  {
    id: "container-key-request",
    from: "container",
    to: "key-broker",
    label: "키 릴리스 요청",
    description: "컨테이너가 자신의 TD 증명에 근거한 키를 요청한다.",
    artifact: "key-release-request",
    plane: "control",
    claimIds: ["policy-result"],
  },
  {
    id: "container-agent-request",
    from: "container",
    to: "guest-agent",
    label: "증명 요청",
    description: "컨테이너가 Guest Agent에 원격 증명을 요청한다.",
    artifact: "attestation-request",
    plane: "workload",
    claimIds: ["tdx-quote-evidence"],
  },
  {
    id: "agent-td-quote",
    from: "guest-agent",
    to: "trusted-domain",
    label: "Quote 생성 요청",
    description: "Guest Agent가 TD의 측정값을 담은 TDX Quote 생성을 요청한다.",
    artifact: "tdx-quote",
    plane: "workload",
    claimIds: ["tdx-quote-evidence"],
  },
  {
    id: "td-attester-evidence",
    from: "trusted-domain",
    to: "attester",
    label: "TDX Quote 제공",
    description: "TDX Quote가 Attester의 Evidence로 전달된다.",
    artifact: "attestation-evidence",
    plane: "attestation",
    claimIds: ["tdx-quote-evidence"],
  },
  {
    id: "attester-verifier-evidence",
    from: "attester",
    to: "verifier",
    label: "Evidence 제출",
    description: "Attester가 TDX Quote를 포함한 Evidence를 Verifier에 보낸다.",
    artifact: "attestation-evidence",
    plane: "attestation",
    claimIds: ["rats-passport", "tdx-quote-evidence"],
  },
  {
    id: "pcs-pccs-collateral",
    from: "pcs",
    to: "pccs",
    label: "원본 collateral 동기화",
    description: "PCCS가 Intel PCS의 인증서, TCB 정보, 폐기 정보를 캐시한다.",
    artifact: "collateral",
    plane: "collateral",
    claimIds: ["dcap-collateral"],
  },
  {
    id: "pccs-verifier-collateral",
    from: "pccs",
    to: "verifier",
    label: "캐시된 collateral 제공",
    description: "Verifier가 PCCS에서 Quote 검증 collateral을 가져온다.",
    artifact: "collateral",
    plane: "collateral",
    claimIds: ["dcap-collateral"],
  },
  {
    id: "endorser-verifier-collateral",
    from: "endorser",
    to: "verifier",
    label: "Endorsement 제공",
    description: "Endorser가 검증 가능한 플랫폼 Endorsement를 제공한다.",
    artifact: "collateral",
    plane: "collateral",
    claimIds: ["dcap-collateral"],
  },
  {
    id: "reference-provider-policy",
    from: "reference-value-provider",
    to: "policy-owner",
    label: "참조값 제공",
    description: "정상 측정값과 평가 기준이 정책에 반영된다.",
    artifact: "collateral",
    plane: "control",
    claimIds: ["policy-result"],
  },
  {
    id: "policy-owner-verifier-policy",
    from: "policy-owner",
    to: "verifier",
    label: "검증 정책 제공",
    description: "정책 소유자가 Verifier에 허용 조건을 제공한다.",
    artifact: "attestation-request",
    plane: "control",
    claimIds: ["policy-result"],
  },
  {
    id: "verifier-relying-result",
    from: "verifier",
    to: "relying-party",
    label: "Attestation Result 전달",
    description: "Verifier가 allow 또는 deny 평가 결과를 Relying Party에 전달한다.",
    artifact: "attestation-result",
    plane: "attestation",
    claimIds: ["rats-passport", "rats-background-check", "policy-result"],
  },
  {
    id: "relying-key-broker-result",
    from: "relying-party",
    to: "key-broker",
    label: "키 공개 결정 전달",
    description: "Relying Party가 Attestation Result에 따른 키 릴리스 결정을 Key Broker에 전달한다.",
    artifact: "attestation-result",
    plane: "control",
    claimIds: ["policy-result", "deny-no-key"],
  },
  {
    id: "key-broker-container-key",
    from: "key-broker",
    to: "container",
    label: "키 릴리스",
    description: "allow일 때만 Key Broker가 workload key를 컨테이너에 보낸다.",
    artifact: "workload-key",
    plane: "control",
    claimIds: ["deny-no-key"],
  },
] as const satisfies readonly RoleEdge[];

export type RoleId = (typeof roles)[number]["id"];
