import type { Sequence } from "./schema";

export const sequences = [
  {
    id: "passport-flow",
    model: "passport",
    label: "패스포트: 증명서 전달",
    description: "Attester가 Verifier가 발급한 Attestation Result를 Relying Party에 제시하는 흐름이다.",
    steps: [
      {
        id: "passport-request",
        from: "relying-party",
        to: "attester",
        label: "증명 요구",
        detail: "Relying Party가 Attester에 필요한 증명 조건을 알린다.",
        artifact: "attestation-request",
        branch: "always",
        claimIds: ["rats-passport"],
      },
      {
        id: "passport-quote",
        from: "guest-agent",
        to: "attester",
        label: "TDX Quote 수집",
        detail: "Guest Agent가 TD에서 TDX Quote를 수집해 Attester Evidence를 준비한다.",
        artifact: "attestation-evidence",
        branch: "always",
        claimIds: ["tdx-quote-evidence"],
      },
      {
        id: "passport-evidence",
        from: "attester",
        to: "verifier",
        label: "Evidence 제출",
        detail: "Attester가 TDX Quote를 포함한 Evidence를 Verifier에 제출해 appraisal을 요청한다.",
        artifact: "attestation-evidence",
        branch: "always",
        claimIds: ["rats-passport", "tdx-quote-evidence"],
      },
      {
        id: "passport-verify",
        from: "verifier",
        to: "attester",
        label: "Evidence 및 collateral 검증",
        detail: "Verifier가 TDX Quote와 PCS 또는 PCCS collateral을 정책 기준으로 평가한다.",
        artifact: "attestation-result",
        branch: "always",
        claimIds: ["dcap-collateral", "policy-result"],
      },
      {
        id: "passport-allow",
        from: "attester",
        to: "relying-party",
        label: "allow 결과 제시",
        detail: "평가가 허용이면 Attester가 Attestation Result를 Relying Party에 제시한다.",
        artifact: "attestation-result",
        branch: "allow",
        claimIds: ["rats-passport", "policy-result"],
      },
      {
        id: "passport-deny",
        from: "attester",
        to: "relying-party",
        label: "deny 결과 제시",
        detail: "평가가 거부이면 deny Attestation Result가 Relying Party에 제시되고 보호 대상 접근은 허용되지 않는다.",
        artifact: "attestation-result",
        branch: "deny",
        claimIds: ["rats-passport", "policy-result"],
      },
    ],
  },
  {
    id: "background-check-flow",
    model: "background-check",
    label: "백그라운드 체크: 결과 조회",
    description: "Relying Party가 Verifier에 Attester의 평가 결과를 직접 조회하는 흐름이다.",
    steps: [
      {
        id: "background-evidence",
        from: "attester",
        to: "verifier",
        label: "Evidence 등록",
        detail: "Attester가 TDX Quote를 포함한 Evidence를 Verifier에 제출한다.",
        artifact: "attestation-evidence",
        branch: "always",
        claimIds: ["rats-background-check", "tdx-quote-evidence"],
      },
      {
        id: "background-collateral",
        from: "pccs",
        to: "verifier",
        label: "collateral 조회",
        detail: "Verifier가 PCCS 캐시 또는 Intel PCS에서 Quote 검증 collateral을 조회한다.",
        artifact: "collateral",
        branch: "always",
        claimIds: ["dcap-collateral"],
      },
      {
        id: "background-request",
        from: "relying-party",
        to: "verifier",
        label: "평가 결과 조회",
        detail: "Relying Party가 Verifier에 Attestation Result를 요청한다.",
        artifact: "attestation-request",
        branch: "always",
        claimIds: ["rats-background-check"],
      },
      {
        id: "background-allow",
        from: "verifier",
        to: "relying-party",
        label: "allow 결과 반환",
        detail: "정책을 만족하면 Verifier가 allow Attestation Result를 Relying Party에 반환한다.",
        artifact: "attestation-result",
        branch: "allow",
        claimIds: ["rats-background-check", "policy-result"],
      },
      {
        id: "background-deny",
        from: "verifier",
        to: "relying-party",
        label: "deny 결과 반환",
        detail: "측정값 또는 TCB 상태가 정책에 맞지 않으면 Verifier가 deny Attestation Result를 반환한다.",
        artifact: "attestation-result",
        branch: "deny",
        claimIds: ["rats-background-check", "policy-result"],
      },
    ],
  },
  {
    id: "tdx-key-release-flow",
    model: "tdx-key-release",
    label: "TDX 키 릴리스",
    description: "Key Broker가 Verifier의 TDX appraisal과 독립적으로 검증된 workload evidence를 정책에 결합해 컨테이너 비밀키를 조건부로 릴리스한다.",
    steps: [
      {
        id: "key-request",
        from: "container",
        to: "guest-agent",
        label: "키 릴리스 요청 전달",
        detail: "컨테이너가 키 식별자와 workload identity를 Guest Agent에 요청 맥락으로 전달한다. 이 값은 attested proof가 아니다.",
        artifact: "key-release-request",
        branch: "always",
        claimIds: ["tdx-quote-evidence"],
      },
      {
        id: "key-broker-request",
        from: "guest-agent",
        to: "key-broker",
        label: "키 릴리스 요청",
        detail: "Guest Agent가 키 릴리스 요청을 Key Broker에 전달한다. 컨테이너가 제공한 identity는 단독으로 신뢰하지 않는다.",
        artifact: "key-release-request",
        branch: "always",
        claimIds: ["tdx-quote-evidence"],
      },
      {
        id: "key-quote",
        from: "guest-agent",
        to: "verifier",
        label: "TDX Quote 생성",
        detail: "Guest Agent가 TD에서 생성한 Quote를 Attester Evidence로 Verifier에 전달한다.",
        artifact: "tdx-quote",
        branch: "always",
        claimIds: ["tdx-quote-evidence"],
      },
      {
        id: "key-verify",
        from: "verifier",
        to: "key-broker",
        label: "정책 평가",
        detail: "Verifier가 PCS 또는 PCCS collateral과 Policy Owner의 기준으로 Quote를 평가해 Attestation Result를 만든다.",
        artifact: "attestation-result",
        branch: "always",
        claimIds: ["dcap-collateral", "policy-result"],
      },
      {
        id: "key-allow",
        from: "key-broker",
        to: "guest-agent",
        label: "키 릴리스",
        detail: "allow Attestation Result를 받으면 Key Broker가 workload key를 Guest Agent에 릴리스한다.",
        artifact: "workload-key",
        branch: "allow",
        claimIds: ["policy-result"],
      },
      {
        id: "key-container-handoff",
        from: "guest-agent",
        to: "container",
        label: "정책 바운드 키 전달",
        detail: "Guest Agent는 독립적으로 검증된 workload evidence가 별도 전달 정책을 만족할 때만 workload key를 컨테이너에 전달한다.",
        artifact: "workload-key",
        branch: "allow",
        claimIds: ["policy-result"],
      },
      {
        id: "key-deny",
        from: "key-broker",
        to: "guest-agent",
        label: "키 미릴리스",
        detail: "deny Attestation Result를 받으면 Key Broker는 Guest Agent에 key-release-response로 거절을 반환하고 workload key를 절대 전송하지 않는다.",
        artifact: "key-release-response",
        branch: "deny",
        claimIds: ["deny-no-key"],
      },
    ],
  },
] as const satisfies readonly Sequence[];

export type SequenceId = (typeof sequences)[number]["id"];
